name: Release to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/hugo
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Install PostCSS dependencies
        run: npm install postcss autoprefixer

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: live

      # - name: Install dependencies
      #   run: npm install

      # - name: Run deploy script
      #   env:
      #     GIT_USER_NAME: "github-actions[bot]"
      #     GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
      #     GH_TOKEN: ${{ secrets.GH_ALPHABETS_PAT }}
      #   run: |
      #     chmod +x deploy.sh
      #     ./deploy.sh
